services:
  docker.db:
    image: postgres:latest
    environment:
      POSTGRES_DB: poll_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - db-docke-data:/var/lib/postgresql/data

volumes:
  db-docke-data:
